### ISSUE TITLE
Advise on initializing the container for Greenplum

### ISSUE THREAD

**Issue by metalshanked** [DataGrip/docker-env#10]
Hi, Looking for any instructions on how to use the docker image for Greenplum.
It seems to get stuck at "Starting (30 sec)"

==== GPINITSYSTEM
20200820:00:30:07:000065 gpinitsystem:greeplum6-f887b7664-x6g5j:gpadmin-[INFO]:-Checking configuration parameters, please wait...
20200820:00:30:07:000065 gpinitsystem:greeplum6-f887b7664-x6g5j:gpadmin-[INFO]:-Reading Greenplum configuration file gpinitsystem_singlenode
20200820:00:30:07:000065 gpinitsystem:greeplum6-f887b7664-x6g5j:gpadmin-[INFO]:-Locale has not been set in gpinitsystem_singlenode, will set to default value
20200820:00:30:07:000065 gpinitsystem:greeplum6-f887b7664-x6g5j:gpadmin-[INFO]:-Locale set to en_US.utf8
20200820:00:30:07:000065 gpinitsystem:greeplum6-f887b7664-x6g5j:gpadmin-[INFO]:-No DATABASE_NAME set, will exit following template1 updates
20200820:00:30:07:000065 gpinitsystem:greeplum6-f887b7664-x6g5j:gpadmin-[INFO]:-MASTER_MAX_CONNECT not set, will set to default value 250
20200820:00:30:07:000065 gpinitsystem:greeplum6-f887b7664-x6g5j:gpadmin-[INFO]:-Detected a single host GPDB array build, reducing value of BATCH_DEFAULT from 60 to 4
20200820:00:30:07:000065 gpinitsystem:greeplum6-f887b7664-x6g5j:gpadmin-[WARN]:-Master open file limit is 1024 should be >= 65535
20200820:00:30:07:000065 gpinitsystem:greeplum6-f887b7664-x6g5j:gpadmin-[INFO]:-Checking configuration parameters, Completed
20200820:00:30:07:000065 gpinitsystem:greeplum6-f887b7664-x6g5j:gpadmin-[INFO]:-Commencing multi-home checks, please wait...
.20200820:00:30:07:000065 gpinitsystem:greeplum6-f887b7664-x6g5j:gpadmin-[FATAL]:-Unable to contact greeplum6-f887b7664-x6g5j: ping: Lacking privilege for raw socket. Script Exiting!
==== host all all 0.0.0.0/0 trust
/home/gpadmin/install_and_start_gpdb.sh: line 29: /data/master/gpsne-1/pg_hba.conf: No such file or directory
==== RESTARTER
20200820:00:30:07:000377 gpstop:greeplum6-f887b7664-x6g5j:gpadmin-[INFO]:-Starting gpstop with args: -a
20200820:00:30:07:000377 gpstop:greeplum6-f887b7664-x6g5j:gpadmin-[INFO]:-Gathering information and validating the environment...
20200820:00:30:07:000377 gpstop:greeplum6-f887b7664-x6g5j:gpadmin-[CRITICAL]:-gpstop failed. (Reason='[Errno 2] No such file or directory: '/data/master/gpsne-1//postgresql.conf'') exiting...
20200820:00:30:07:000382 gpstart:greeplum6-f887b7664-x6g5j:gpadmin-[INFO]:-Starting gpstart with args: -a
20200820:00:30:07:000382 gpstart:greeplum6-f887b7664-x6g5j:gpadmin-[INFO]:-Gathering information and validating the environment...
20200820:00:30:07:000382 gpstart:greeplum6-f887b7664-x6g5j:gpadmin-[CRITICAL]:-gpstart failed. (Reason='[Errno 2] No such file or directory: '/data/master/gpsne-1//postgresql.conf'') exiting...
/home/gpadmin
==== DONE!
STARTING... (about 30 sec)

**Comment by tjlee** [comment]
@metalshanked what image are you trying to build/launch?

**Comment by tjlee** [comment]
No details.
