### ISSUE TITLE
version 12.5 available?

### ISSUE THREAD

**Issue by danielveraec** [DataGrip/docker-env#11]
Thank you for the configuration.
I would like to find an image with version 12.5. 🙏🏻
Do you have it available?

**Comment by tjlee** [comment]
What image do you need?

**Comment by danielveraec** [comment]
Hi @tjlee. I need a container with sybase ase 12.5.  Is it possible?
I know this version is obsolete but I need test a project in this version.

**Comment by tjlee** [comment]
I have no installation files for Sybase ASE 12.5 to put them into docker container
