### ISSUE TITLE
[ASE 16] Add -T11889 flag to sybase start script

### ISSUE THREAD

**Issue by MaceWindu** [DataGrip/docker-env#12]
Recently ASE16 image started to crash for us on startup when run in linux host.
I've made some search and found this topic https://answers.sap.com/questions/13286419/ase-16-signal-11-stack-trace-snapvalidate-kba-3018.html

I would recommend to add ` -T11889` start flag to `/opt/sybase/ASE-16_0/install/RUN_MYSYBASE` (tried it and it helps) to workaround this issue.

**Comment by Jesse0Michael** [comment]
Thank you for the work around, @MaceWindu 

I overwrote the `/opt/sybase/ASE-16_0/install/RUN_MYSYBASE` script with the `-T11889` option in a docker image based off of `datagrip/sybase:16.0`  using `COPY RUN_MYSYBASE /opt/sybase/ASE-16_0/install` and it worked! I'm back in busines now!

**Comment by tjlee** [comment]
I'll try to investigate since we don't experience the issue in our environment.

**Comment by tjlee** [comment]
You can extent the current image as you wish. In our team we have no such issues.

**Comment by bbabiack** [comment]
> Thank you for the work around, @MaceWindu
> 
> I overwrote the `/opt/sybase/ASE-16_0/install/RUN_MYSYBASE` script with the `-T11889` option in a docker image based off of `datagrip/sybase:16.0` using
> 
> ```
> COPY RUN_MYSYBASE /opt/sybase/ASE-16_0/install
> ```
> 
> and it worked! I'm back in busines now!

For those of you having issues with this using Docker desktop on Windows, make sure you have the line endings for the file set to LF before you copy the file over. CRLF will result in an error that it cannot find the files/directories

**Comment by doresome** [comment]
I found this issue did not affect docker v19 but did affect v20+
