### ISSUE TITLE
/opt/mssql/bin/sqlservr-setup: not found

### ISSUE THREAD

**Issue by rizkyario** [DataGrip/docker-env#3]
I wasn't able to build the Dockerfile successfully. Having problem in step 6
`Step 6/13 : RUN /opt/mssql/bin/sqlservr-setup --accept-eula --set-sa-password
 ---> Running in d3a93524a9eb
/bin/sh: 1: /opt/mssql/bin/sqlservr-setup: not found
The command '/bin/sh -c /opt/mssql/bin/sqlservr-setup --accept-eula --set-sa-password' returned a non-zero code: 127`
It seems that the latest microsoft/mssql-server-linux does not have sqlservr-setup

**Comment by tjlee** [comment]
@rizkyario Hi,
You're right. Microsoft has changed installation flow. We'll fix it soon. Thank you.

**Comment by tjlee** [comment]
@rizkyario Fixed. 
Pull the latest version from Docker Hub. 
Thank you.

**Comment by rizkyario** [comment]
@tjlee Great! Your latest version from Docker Hub does work indeed. But when I try to build the image from its source code, I encountered this error.

`
Step 6/13 : RUN /opt/mssql/bin/sqlservr.sh --accept-eula --set-sa-password
 ---> Running in 40c49ff47a67
Configuring Microsoft(R) SQL Server(R)...
Configuration complete.
This is an evaluation version.  There are [175] days left in the evaluation period.
+++ NT HARD ERROR (0x50000018) +++
    Parameter 0: 0x4005cddd0 [Your SQL Server installation is either corrupt or has been tampered with (Unknown package id).
Please uninstall then re-run setup to correct this problem]
    Parameter 1: 0x4005cddc0 [SQL Server]
    Parameter 2: 0x10010
    Parameter 3: 0xffffffff
sqlservr: Debugger.cpp:578: static void Debugger::Print(const void *, unsigned int): Assertion `"A serious error condition has
been encountered." == nullptr' failed.
'
Any idea what's wrong?
