### ISSUE TITLE
Logic for startup timeout not working

### ISSUE THREAD

**Issue by jmoscato** [DataGrip/docker-env#4]
Hi,

The entrypoint.sh script is very useful. However, the logic for the startup timeout is not working for me. The while loop is always taking 30 seconds despite the actual mssql-server instance starting up faster than that.

There seems to be a few problems:
- the i variable appears to be treated as a string so it is being concatenated instead of incremented
- the while test to check for the timeout isn't doing the desired logic
- the string indicating startup has finished has changed

I would be happy to create a pull request, or here are some suggested changes:

```bash
#waiting for mssql to start
export STATUS=0
declare -i TIMEOUT=30
declare -i i=0
while [[ $STATUS -eq 0 && (i -lt TIMEOUT) ]]; do
	sleep 1
	i=i+1
	STATUS=$(grep 'Service Broker manager has started' /var/opt/mssql/log/setup*.log | wc -l)
	echo "Waiting $i..."
done
```

**Comment by tjlee** [comment]
Fixed with https://github.com/DataGrip/docker-env/commit/549cd4ef5c54d57bb9537ce05235dec8653a34c9
