### ISSUE TITLE
Stop command no longer required for mssql-server-linux?

### ISSUE THREAD

**Issue by jmoscato** [DataGrip/docker-env#5]
Hi,

The trap statement at the end of the entrypoint.sh script contains a stop command that doesn't seem to be working for me:

```
/opt/mssql/bin/sqlservr stop
This is an evaluation version.  There are [168] days left in the evaluation period.
sqlservr: Another instance of the application is already running.
```

Perhaps the sqlservr command has changed since the script was written, so an explicit stop is no longer needed?

**Comment by tjlee** [comment]
Possible fix in https://github.com/DataGrip/docker-env/commit/f2b877d14970c9489eaa4fd909b37b0272fba53b
