### ISSUE TITLE
datagrip/sybase:16.0 character set is iso_1 instead of UTF8

### ISSUE THREAD

**Issue by MaceWindu** [DataGrip/docker-env#9]
Original dockerfile nguoianphu/docker-sybase uses [utf8](https://github.com/nguoianphu/docker-sybase/blob/master/assets/sybase-ase.rs#L21) but this image is built with iso_1 character set (could be seen in second resultset returned by `sp_helpsort`).
Was it intentional change or rs file was missing during image build?

We use this image for our tests and it fails couple of unicode-related test for us due to this.

**Comment by tjlee** [comment]
@MaceWindu 
RS file was missing during image build. If you can provide it I can rebuild final image.

**Comment by MaceWindu** [comment]
Can you use file I linked from original image?

**Comment by tjlee** [comment]
Yes, I'll try to do it.

**Comment by tjlee** [comment]
>  Was it intentional change or rs file was missing during image build?

Current image is built upon original one, `nguoianphu/docker-sybase`. The only difference is extension scripts to create additional users. 

By the way I launched original image I checked out server character set. It looks like server character set is `iso_1` too:
![image](https://user-images.githubusercontent.com/1133087/65139626-a17cf480-da15-11e9-9629-121b846c246f.png)

**Comment by tjlee** [comment]
If you need to change charset you can invoke the following commands on your server
- invoke charset with
```
export LD_LIBRARY_PATH=/opt/sybase/OCS-16_0/lib3p64/
/opt/sybase/ASE-16_0/bin//charset -Usa -PmyPassword -SMYSYBASE binary.srt utf8
```
- invoke isql with
```
/opt/sybase/OCS-16_0/bin/isql -Usa -PmyPassword -SMYSYBASE
>sp_configure 'default sortorder id', 50, 'utf8'
>go
```
- restart sybase server

![image](https://user-images.githubusercontent.com/1133087/65141877-31bd3880-da1a-11e9-93b3-6795c7652cd1.png)

**Comment by MaceWindu** [comment]
I hoped to avoid it as it involves server restart :) ah well, looks like I cannot avoid it

**Comment by tjlee** [comment]
On very first server start you can change encoding and restart server. 

See https://github.com/DataGrip/docker-env/blob/master/sybase/16.0/entrypoint.sh for initialisation logic
